language: csharp

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      # Install LLVM.
      - libllvm5.0
      - llvm-5.0
      - llvm-5.0-tools
      - clang-5.0

install:
  # Set the LLVM_PATH variable.
  - export LLVM_PATH=$(llvm-config-5.0 --libdir)
  - echo ${LLVM_PATH}
  # Restore nuget packages
  - make nuget

script:
  # Compile supporting macros.
  - make dsl

  # Build Flame using csc (Release)
  - make

  # Run the tests
  - make test

  # Run LLVM-specific tests.
  - make test-llvm
