language: csharp

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      # Install LLVM.
      - libllvm5.0

install:
  # Restore nuget packages
  - make nuget

script:
  # Compile supporting macros.
  - make dsl

  # Build Flame using csc (Release)
  - make

  # Run the tests
  - make test

  # Run LLVM-specific tests.
  - LLVM_PATH=/usr/lib/llvm-5.0/lib make test-llvm
