language: csharp

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-7
    packages:
      # Install LLVM.
      - libllvm7
      - llvm-7
      - llvm-7-tools
      - clang-7

install:
  # Set the LLVM_PATH variable.
  - export LLVM_PATH=$(llvm-config-7 --libdir)
  - echo ${LLVM_PATH}
  # Restore nuget packages
  - make nuget

script:
  # Compile supporting macros.
  - make dsl

  # Build Flame using csc (Release)
  - make

  # Run the tests
  - make test

  # Run LLVM-specific tests.
  - make test-llvm
