language: csharp
solution: Flame.Cecil/Flame.Cecil.sln
install:
  - curl -L https://github.com/jonathanvdc/Flame/releases/download/v0.8.3/dsc.zip > dsc.zip
  - unzip dsc.zip -d bin_dsc
  - git clone https://github.com/jonathanvdc/compare-test
  - nuget restore Flame.Cecil/Flame.Cecil.sln
script:
  # Perform one build to check that Flame is buildable
  - ./BuildCI.sh bin_dsc/dsc.exe
  # Perform a second build to make sure that Flame can bootstrap
  - ./BuildCI.sh dsc/bin/Release/dsc.exe
  # Build compare-test, with -O3, to ensure that aggressive optimizations
  # work for a real-life application. Use --debug to catch some incorrect
  # optimizations at compile-time.
  - mono dsc/bin/Release/dsc.exe compare-test/src/compare-test.dsproj -O3 --debug
  # Run the tests
  - mono compare-test/src/bin/compare-test.exe all-tests.test
