language: csharp
solution: Flame.Cecil/Flame.Cecil.sln
install:
  - curl -L https://github.com/jonathanvdc/Flame/releases/download/v0.9.6/dsc.zip > dsc.zip
  - unzip dsc.zip -d bin_dsc
  - git clone https://github.com/jonathanvdc/compare-test
  - nuget restore Flame.Cecil/Flame.Cecil.sln
script:
  # Perform one build to check that Flame is buildable
  - ./BuildCI.sh bin_dsc/dsc.exe -O1
  # Perform a second build to make sure that Flame can bootstrap
  # and turn on -O3 optimizations.
  - ./BuildCI.sh dsc/bin/Release/dsc.exe -O3
  # Perform a third build to make sure that Flame can bootstrap with
  # aggressive optimizations turned on.
  - ./BuildCI.sh dsc/bin/Release/dsc.exe -O3
  # Build compare-test, with -O3, to ensure that aggressive optimizations
  # work for a real-life application. Use --debug to catch incorrect
  # optimizations at compile-time.
  - mono dsc/bin/Release/dsc.exe compare-test/src/compare-test.dsproj -O3 --debug
  # Run the tests
  - mono compare-test/src/bin/compare-test.exe all-tests.test -j
