install:
  - curl -L https://github.com/jonathanvdc/Flame/releases/download/v0.7.3/dsc.zip > dsc.zip
  - 7z x dsc.zip -obin_dsc
  - git clone https://github.com/jonathanvdc/compare-test
  - nuget restore Flame.Cecil\Flame.Cecil.mono.sln
build_script:
  # Perform one build to check that Flame is buildable
  - BuildCI.bat bin_dsc\dsc\dsc.exe
  # Perform a second build to make sure that Flame can bootstrap
  - BuildCI.bat dsc\bin\Release\dsc.exe
  # Build compare-test
  - dsc\bin\Release\dsc.exe compare-test\src\compare-test.dsproj
  # Run the tests
  - compare-test\src\bin\compare-test.exe all-tests.test
