version: 0.11.0.{build}

image:
  - Visual Studio 2017

environment:
  op_build_user: "jonathanvdc"
  op_build_user_email: "jonathan.vdc@outlook.com"
  access_token:
    secure: g+uq4ZWbxSQPIvxKd2swP1ce1rKaY/OQh6Rn2emgCv3ke5QYt7uILm5JsC8CA9GE

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

clone_depth: 10

before_build:
  # Install DocFX.
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -and $env:APPVEYOR_REPO_BRANCH -eq "master")
        {
            choco install docfx -y
        }

build_script:
  # Generate a NuGet package version number.
  - echo %APPVEYOR_REPO_TAG%
  - C:\Python34\python.exe Tools\CI\version-number.py %APPVEYOR_BUILD_VERSION% > pkg-version.txt
  - set /p PKG_VERSION=<pkg-version.txt
  - echo %PKG_VERSION%

  # Restore NuGet packages.
  - nuget restore src/Flame.sln
  # Build supporting macros.
  - msbuild /p:Configuration=Release /verbosity:quiet /nologo src/FlameMacros/FlameMacros.csproj
  # Compile macro applications.
  - C:\cygwin\bin\make dsl RUN_EXE=""
  # Build Flame.
  - msbuild /p:Configuration=Release /verbosity:quiet /nologo src/Flame.sln
  # Run the tests.
  - src\UnitTests\bin\Release\net45\UnitTests.exe -h
  - src\UnitTests\bin\Release\net45\UnitTests.exe all

after_build:
  # Create NuGet packages
  - nuget pack -Version %PKG_VERSION% src/Flame.nuspec
  - nuget pack -Version %PKG_VERSION% src/Flame.Clr.nuspec
  - nuget pack -Version %PKG_VERSION% src/Flame.Ir.nuspec

  # Build docs using DocFX and deploy them to GitHub pages. (Based on https://github.com/docascode/docfx-seed/blob/master/appveyor.yml)
  - ps: |
        if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE -and $env:APPVEYOR_REPO_BRANCH -eq "master")
        {
            # & nuget install docfx.console -Version 2.18.4 -Source https://www.myget.org/F/docfx/api/v3/index.json
            # & docfx.console.2.18.4\tools\docfx docfx.json
            & docfx docs/docfx.json
            if ($lastexitcode -ne 0){
                throw [System.Exception] "docfx build failed with exit code $lastexitcode."
            }

            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
            git config --global user.email $env:op_build_user_email
            git config --global user.name $env:op_build_user
            git clone https://github.com/$($env:APPVEYOR_REPO_NAME).git -b gh-pages origin_site -q
            Copy-Item origin_site/.git docs/_site -recurse
            CD docs/_site
            git add -A 2>&1
            git commit -m "CI Updates" -q
            git push origin gh-pages -q
        }
