version: 0.11.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

build_script:
  - set SEMVER=%APPVEYOR_BUILD_VERSION%
  - echo %APPVEYOR_REPO_TAG%
  # Build packages as SEMVER-ci{build}
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $True) { $env:PKG_VERSION = $env:SEMVER; } else { $env:PKG_VERSION = "$($env:SEMVER)-ci$($env:APPVEYOR_BUILD_NUMBER)"; }
  - echo %PKG_VERSION%

  # Get the C# compiler's path and put it in an environment variable.
  - where csc > csc-address.txt
  - set /p CSC_PATH=<csc-address.txt
  - echo %CSC_PATH%
  # Restore NuGet packages.
  - nuget restore Flame.sln
  # Build supporting macros.
  - msbuild /p:Configuration=Release /verbosity:quiet /nologo FlameMacros/FlameMacros.csproj
  # Compile macro applications.
  - C:\cygwin\bin\make dsl RUN_EXE=""
  # Build Flame.
  - msbuild /p:Configuration=Release /verbosity:quiet /nologo Flame.sln
  # Run the tests.
  - UnitTests\bin\Release\UnitTests.exe all "--csc-path=%CSC_PATH%"

after_build:
  # Create NuGet packages
  - nuget pack -Version %PKG_VERSION% Flame.nuspec
